# Generated by Django 3.0.1 on 2019-12-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choic',
            new_name='Choice',
        ),
    ]
